### ISSUE TITLE
Riot API V3 deprecation

### ISSUE THREAD

**Issue by lmachens** [lmachens/trophy-hunter#40]
> We are adding a new security layer for the privacy of players. In order to do so, we are releasing a new version for several of the Riot Games APIs. All v3 endpoints that have a v4 counterpart will be deprecated in on January 28th, 2019. Please see the announcement for additional details.
https://www.riotgames.com/en/DevRel/player-universally-unique-identifiers-and-a-new-security-layer

We have to update all API requests.

**Comment by lmachens** [comment]
Sadly this is a lot of work and it is unclear how we can solve it.
Riot encrypted `summonerId` and `accountId`.

**Comment by Rayth** [comment]
Riot support might have an answer for this? They must know that these 2 will be crucial for developers.

**Comment by lmachens** [comment]
The problem is, that we get only the decrypted `accountId` from the overwolf api. But it is not possible to get the summoner with that id anymore. Only solution is to get the summoner by name:
https://developer.riotgames.com/api-methods/#summoner-v4/GET_getBySummonerName
There is a discussion in the overwolf slack about this issue (privat channel; can not link).
