### ISSUE TITLE
Iron rank is not displayed in Overlay

### ISSUE THREAD

**Issue by lmachens** [lmachens/trophy-hunter#58]
The rank for pantheon and blitzcrank is not visible. Both summoners are iron.
![image](https://user-images.githubusercontent.com/10058950/50886407-a0a8b300-13f0-11e9-9124-01f39341421d.png)

**Comment by MarlonWelter** [comment]
Right, that is the new ranking tier from season 9. Do you already have an idea what's causing the problem?

**Comment by lmachens** [comment]
I guess it is just a missing graphic file
