### ISSUE TITLE
champion.gg api is not available anymore

### ISSUE THREAD

**Issue by lmachens** [lmachens/trophy-hunter#76]
**The problem**
We use it for champion stats and guides like win rate, damage composition or runes.
Right now we fetch their api twice a day and generate our own champions stats.
See https://github.com/lmachens/trophy-hunter/blob/master/imports/api/champions/server/_updateChampionGGStats.js
But https://api.champion.gg/ is not available anymore. 

**The idea**
We generate our own champion stats and guides. For stats like win rate it should be very easy. We already did it for first blood and snowball stats:
https://github.com/lmachens/trophy-hunter/blob/master/imports/api/champions/server/_updateFirstBloodStats.js
https://github.com/lmachens/trophy-hunter/blob/master/imports/api/champions/server/_updateSnowballStats.js
But the rune and item guides are more difficult.

**Open questions**

1. Should we calculate these stats based on trophy hunter matches or on all matches of a tier like diamond/platinum?

1. How can we calculate the item and rune guides?

**Comment by MarlonWelter** [comment]
I think the champion winrates are much more important than the item and rune guides. So I would suggest doing that step first, then the other step afterwards.

1. I would just calculate them on our own trophyhunter games. I like that idea and also it should be easier to implement and have no extra requests to RIOT api.

My approach to it would be:
a) Create helper functions, that extract the relevant information for the statistics from a match and give those back as a result.
b) Create one or more Statistics objects that are stored in the database and hold all our statistics (like champion vs champion winrates etc).
c) Create a updater function: this one calls the helper function with a new match and updates the statistics object afterwards.

This way after calling extendMatchResults, we can call the updater function and we start creating our own statistics.

2. I could do some cool statistical stuff there actually (the champion.gg stats were not very good in a way), so maybe it is even a chance for us if we can do some good and interesting statistics here. But as I said I would first focus on the winrates.

**Comment by lmachens** [comment]
Ok good, thx.

But before we start with it, let us think about the item and rune guides.
Maybe it makes sense to use an additional service for it which we can use for the stats too.

I think we have to save all possible item and rune combinations and calculate the win rate for that.
This is how it could work:

**Analyse a match**
We can use our trophy check service and seperate the logic by map (ARAM, Howling, Rift) and role (depends on map).
**Extract stats for every champ**
First get win/loss, first blood/no first blood, average kills...
Then connect these stats with starter/final items and runes.
Example:
Cassiopeia won with 6/5/2 on Summoners Rift with some runes, starter and final items.
**Update champion stats**
We can update the rates like we already do for first blood rate.
In addition we save the runes and items in a subset of the champion.
These subsets have the same stats like the champion.

Our current structure looks like this:
![image](https://user-images.githubusercontent.com/10058950/51191196-31e1c300-18e4-11e9-900b-5ecacb9d39a4.png)

**Comment by Rayth** [comment]
Both using trophy hunter games and all games have their merit.
By using only TH games, you can update stats pretty much straight away (say a new champion has 50% win rate in 10 games, then players win 10 more games you can update he win% right away for that champion). However there aren't as many people using TH as we would like to make the stats and such for this foolproof and our own stats may vary massively from riot's data. 

As for guides, couldn't we get the TH site running and have a guide section for players to post guides themselves, then have a sort of 'voting' system for the best guide which will appear on the app.

**Comment by lmachens** [comment]
It's an issue again

**Comment by lmachens** [comment]
Replaced in https://github.com/lmachens/trophy-hunter/commit/1d5dc634945607910e49e3af1f56cbfe0d9f9edc
