### ISSUE TITLE
Make background image customizable

### ISSUE THREAD

**Issue by MarlonWelter** [lmachens/trophy-hunter#86]
idea from mudikp:

* Let users be able to choose their own background image for trophyhunter app.

**Comment by lmachens** [comment]
Which background is he talking about? and how does he wants to customize it (select from existing backgrounds / upload new one)?

**Comment by MarlonWelter** [comment]
He wants to upload his own background image.

**Comment by lmachens** [comment]
And for which view? In the overlay/app?
I don't think it is a good idea to make it customizable. This takes a lot of work including views for uploading the background.

**Comment by MarlonWelter** [comment]
Yea, its definitely not a high priority.

**Comment by J-Antonio-Glez-Guerra** [comment]
I can do this. codemill$50. In wich view do you need the images??
